isxcode/isx-cli

cmd/pr.go

GH-34 在pr的comment中添加 GH-xxx 

---

cmd/clone.go

GH-53 isx clone 添加和修改完remote后，使用git branch --set-upstream-to=upstream/main main 重新绑定main分支

---

cmd/login.go

GH-44 isx login提示，用户不能使用邮箱登录，必须使用github account

---

cmd/pull.go

GH-38 新增命令 isx pull xxx

---

cmd/pull.go

GH-69 isx pull 不需要制定issue_number，默认拉取当前分支

---

cmd/format.go
cmd/pull.go

GH-72 获取当前分支，通过viper获取项目路径

---

cmd/format.go

GH-75 isx format 无法提交子模块代码

---

cmd/root.go
cmd/upgrade.go

GH-78 添加至匠云模块

---

cmd/build.go
cmd/checkout.go
cmd/clone.go
cmd/format.go
cmd/git.go
cmd/login.go
cmd/now.go
cmd/pr.go
cmd/pull.go
cmd/root.go
cmd/upgrade.go
common/common.go
common/github.go
git/command.go

GH-82 代码优化

---

README.md
cmd/build.go
cmd/delete.go
cmd/gradle.go
cmd/login.go
cmd/now.go
cmd/pull.go
cmd/remove.go
git/command.go

GH-68 新增命令 isx delete 123，删除upstream仓库中的需求分支

---

install.sh

GH-90 升级版本到1.1.0

---

install.sh

GH-93 修复isx upgrade 下载的命令无法使用

---

git/command.go

GH-99 now命令 输出内容尾部多出一个 %

---

cmd/format.go
cmd/root.go
cmd/upgrade.go

GH-105 添加至慧云项目

---

cmd/run.go

GH-112 run命令启动项目时 镜像时区为UTC 期望设置为CST (+08:00 Asia/Shanghai)

---

cmd/db.go

GH-81 新增命令 isx db 

---

README.md

GH-96 支持 brew install isx

---

install.sh

GH-98 直接使用mv更新，没有更新版本号

---

cmd/delete.go

GH-120 isx delete 返回410Gone

---

cmd/sync.go

GH-123 增加分支同步功能, 可能供其它指令使用

---

README.md
git/command.go

GH-125 isx now命令低版本git不支持

---

README.md
cmd/backend.go
cmd/clean.go
cmd/install.go
cmd/package.go

GH-129 支持package/clean/backend/install 等命令

---

README.md
cmd/choose.go
cmd/root.go
cmd/upgrade.go
install.sh

GH-132 添加子项目,至视云,至数云,至慧云

---

cmd/root.go

GH-135 修改至数云地址

---

.github/workflows/package.yml
install.sh

GH-138 自动打包推送到阿里云oss中

---

.github/workflows/package.yml

GH-141 修复github action无法启动

---

.github/workflows/package.yml
README.md

GH-144 添加readme文件下载路径

---

cmd/format.go
cmd/push.go
cmd/upgrade.go

GH-147 将isx format 改为isx push

---

README.md
cmd/build.go
cmd/checkout.go
cmd/choose.go
cmd/db.go
cmd/delete.go
cmd/git.go
cmd/home.go
cmd/pr.go
cmd/pull.go
cmd/push.go
cmd/run.go
cmd/upgrade.go
install.sh

GH-150 install脚本异常

---

cmd/backend.go
cmd/checkout.go
cmd/format.go
cmd/gradle.go
cmd/install.go
cmd/package.go
cmd/push.go
install.sh

GH-161 兼容windows开发

---

install.sh

GH-164 isx upgrade windows不需要sudo权限

---

install.sh

GH-167 windows授权路径异常

---

cmd/backend.go
cmd/format.go
cmd/gradle.go
cmd/install.go
cmd/package.go
cmd/push.go

GH-170 使用项目下的gradlew.bat

---

cmd/install.go

GH-173 兼容windows路径

---

cmd/install.go

GH-176 支持bat脚本

---

cmd/backend.go
cmd/format.go
cmd/gradle.go
cmd/package.go
cmd/push.go
install.sh

GH-179 windows路径异常问题

---

README.md
cmd/checkout.go
cmd/clone.go
cmd/delete.go
cmd/format.go
cmd/git.go
cmd/gradle.go
cmd/install.go
cmd/now.go
cmd/package.go
cmd/pull.go
cmd/push.go
cmd/remove.go
cmd/run.go
cmd/start.go
git/command.go

GH-187 windows路径异常

---

cmd/build.go
cmd/clone.go

GH-190 clone不兼容windows

---

cmd/clone.go

GH-195 windows路径兼容问题

---

cmd/clone.go
common/color.go
common/common.go

GH-194 isx clone 默认下载到当前路径

---

cmd/autotest.go

GH-45 新增自动化测试命令 isx autotest

---

cmd/delete.go

GH-199 delete支持-f命令和-a命令

---

cmd/pr.go

GH-203 自动提交pr到main分支

---

cmd/issue.go

GH-97 支持 isx issue  列出所有的本地分支 和对应的issue说明

---

cmd/clone.go
cmd/fork.go
common/common.go
common/github.go
github/common.go
github/entity.go
github/fork.go

GH-198 自动帮用户fork项目

---

cmd/checkout.go
cmd/clone.go
cmd/delete.go
cmd/pr.go
cmd/sync.go
cmd/upgrade.go
common/common.go

GH-33 github token 安全性问题，本地会暴露

---

cmd/issue.go
github/common.go

GH-220 部分命令未兼容 token验证 

---

.github/workflows/package.yml
README.md
install.sh

GH-224 支持windows的arm架构

---

.github/workflows/package.yml
README.md
cmd/clone.go
cmd/db.go
cmd/fork.go
cmd/issue.go
cmd/sync.go
common/color.go
common/common.go
common/github.go
github/common.go
github/entity.go
github/fork.go

GH-227 修复clone异常

---

cmd/clone.go

GH-233 clone异常

---

.github/workflows/package.yml
README.md
cmd/checkout.go
cmd/clean.go
cmd/clone.go
cmd/db.go
cmd/delete.go
cmd/fork.go
cmd/git.go
cmd/issue.go
cmd/pr.go
cmd/pull.go
cmd/push.go
cmd/remove.go
cmd/sync.go
cmd/upgrade.go
common/color.go
common/common.go
common/github.go
github/common.go
github/entity.go
github/fork.go
install.sh

GH-214 isx clean会直接删除~/.zhiqingyun目录，给出确认提示

---

cmd/install.go
cmd/package.go

GH-239 windows下isx install/package日志乱码问题

---

cmd/server.go
cmd/web.go
cmd/website.go

GH-242 添加打开官网的命令

---

README.md

GH-245 优化readme文档

---

cmd/root.go

GH-251 [Feature] 添加至数云项目

---

cmd/root.go

GH-254 [Feature] 替换至慧云仓库
